# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpQQ3HhfGKGYGf8oDd6WvPc1eevP1J0k
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import random

# 1. 웹사이트 기본 설정
st.set_page_config(page_title="환승 마니또 : X-Signal", layout="wide")

# 2. [수정 포인트] 참여자 실제 명단
# 여기에 30명의 이름을 나열하세요.
PARTICIPANTS = [
    "단비", "창우", "주희", "온유", "유민", "주형",
    "예슬", "도현", "성현", "신영", "준일", "주황",
    "진수", "영찬", "다연", "예원", "주현", "총명",
    "연제", "윤아", "마리아", "규진", "주한", "건양",
]

# 3. 데이터베이스 초기화 (최초 1회 실행)
if 'db' not in st.session_state:
    # 마니또 섞기 (자기 자신 제외)
    targets = PARTICIPANTS[:]
    while True:
        random.shuffle(targets)
        if all(PARTICIPANTS[i] != targets[i] for i in range(len(PARTICIPANTS))):
            break

    db = {}
    for i, name in enumerate(PARTICIPANTS):
        target_name = targets[i]
        # 닉네임 설정: 마니또이름 + "또"
        custom_nickname = f"{target_name}또"

        db[name] = {
            "nickname": custom_nickname,
            "target": target_name,
            "status": "아직 지목되지 않았습니다.",
            "messages": []
        }
    st.session_state.db = db
    st.session_state.global_chat = []

# --- 화면 상단 타이틀 ---
st.title("💘 환승 마니또 : X-Signal")
st.markdown("---")

# 4. 로그인 로직
if 'user' not in st.session_state:
    st.subheader("로그인")
    login_name = st.selectbox("당신의 이름을 선택하세요", ["선택하세요", "운영자"] + PARTICIPANTS)

    if login_name == "운영자":
        # 요청하신 대로 비밀번호를 4321로 설정했습니다.
        password = st.text_input("운영자 비밀번호를 입력하세요", type="password")
        if st.button("운영자 로그인"):
            if password == "4321":
                st.session_state.user = "운영자"
                st.rerun()
            else:
                st.error("비밀번호가 틀렸습니다.")

    elif login_name != "선택하세요":
        if st.button("입장하기"):
            st.session_state.user = login_name
            st.rerun()

# 5. 로그인 성공 후 화면
else:
    user = st.session_state.user

    # [A. 운영자 화면]
    if user == "운영자":
        st.sidebar.title("🕶️ 관제 센터")
        if st.sidebar.button("로그아웃"):
            del st.session_state.user
            st.rerun()

        m_tab1, m_tab2, m_tab3 = st.tabs(["📊 매칭 현황", "🕵️ 실시간 감시", "📢 공지사항"])

        with m_tab1:
            st.subheader("전체 마니또 매칭표")
            m_list = []
            for s, info in st.session_state.db.items():
                m_list.append({
                    "본명": s,
                    "닉네임": info['nickname'],
                    "챙길 대상(마니또)": info['target'],
                    "지목 상태": info['status']
                })
            st.table(pd.DataFrame(m_list))

        with m_tab2:
            st.subheader("최근 전달된 쪽지")
            for r, info in st.session_state.db.items():
                if info['messages']:
                    st.write(f"**{r}**에게 온 메시지: {info['messages'][-1]}")

        with m_tab3:
            notice_text = st.text_input("전체 공지 메시지")
            if st.button("공지 전송"):
                st.session_state.global_chat.append(f"🚨 [공지] {notice_text}")
                st.success("공지가 등록되었습니다.")

    # [B. 일반 사용자 화면]
    else:
        my_data = st.session_state.db[user]

        # 사이드바 정보
        st.sidebar.title(f"👤 {user}")
        st.sidebar.write(f"나의 닉네임: **{my_data['nickname']}**")
        st.sidebar.info(f"내가 챙길 사람: **{my_data['target']}**")
        st.sidebar.markdown(f"**현재 내 상태:**\n{my_data['status']}")

        if st.sidebar.button("로그아웃"):
            del st.session_state.user
            st.rerun()

        # 메인 탭 구성
        tab1, tab2, tab3 = st.tabs(["💬 단체 익명톡", "💌 X-메시지", "🎯 오늘의 선택"])

        # 탭 1: 단체톡
        with tab1:
            st.subheader("전체 익명 채팅방")
            chat_msg = st.text_input("내용 입력", key="global_input")
            if st.button("전송"):
                if chat_msg:
                    st.session_state.global_chat.append(f"[{my_data['nickname']}] {chat_msg}")
                    st.rerun()

            for m in reversed(st.session_state.global_chat):
                st.write(m)

        # 탭 2: 마니또에게 쪽지
        with tab2:
            st.subheader(f"내 마니또({my_data['target']})에게 쪽지 보내기")
            to_send = st.text_area("익명으로 전달됩니다.", key="secret_area")
            if st.button("쪽지 보내기"):
                if to_send:
                    target = my_data['target']
                    st.session_state.db[target]['messages'].append(f"X로부터: {to_send}")
                    st.success("상대방의 보관함에 쪽지를 넣었습니다.")

            st.divider()
            st.subheader("나에게 온 쪽지함")
            for m in reversed(my_data['messages']):
                st.write(f"📩 {m}")

        # 탭 3: 정답 맞히기
        with tab3:
            st.subheader("누가 나를 챙겨주고 있을까?")
            guess = st.selectbox("의심되는 사람의 본명을 선택하세요", ["선택하세요"] + PARTICIPANTS)

            if st.button("지목하기"):
                if guess == "선택하세요":
                    st.warning("이름을 먼저 선택해주세요.")
                else:
                    real_x = ""
                    for k, v in st.session_state.db.items():
                        if v['target'] == user:
                            real_x = k

                    if guess == real_x:
                        st.balloons()
                        st.success(f"맞았습니다! {guess}님은 당신의 마니또입니다. 🎯")
                        st.session_state.db[real_x]['status'] = "당신의 마니또가 당신을 선택했습니다! ❤️"
                    else:
                        st.error(f"틀렸습니다! {guess}님은 당신의 마니또가 아닙니다. 🤫")
                        if real_x:
                            st.session_state.db[real_x]['status'] = "당신의 마니또가 당신을 선택하지 않았습니다. 💔"