# -*- coding: utf-8 -*-
"""app3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpQQ3HhfGKGYGf8oDd6WvPc1eevP1J0k
"""

import streamlit as st
import pandas as pd
import random

# --- 1. 참가자 설정 ---
PARTICIPANTS = ["단비", "창우", "주희", "온유", "유민", "주형", "예슬", "도현", "성현", "신영", "준일", "주황", "진수", "영찬", "다연", "예원", "주현", "총명", "연제", "윤아", "마리아", "규진", "주한", "건양"]

# 귀여운 프로필 이미지 리스트 (24개 랜덤 배정)
AVATARS = [f"https://api.dicebear.com/7.x/adventurer/svg?seed={name}" for name in PARTICIPANTS]

# --- 2. 핑크 몽글몽글 디자인 (CSS) ---
st.set_page_config(page_title="💖 X-Signal", layout="centered")

st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap');

    .stApp { background: linear-gradient(180deg, #fff5f7 0%, #ffe4e8 100%); }

    /* 말풍선 스타일 및 줄깨짐 방지 */
    .chat-row { display: flex; margin-bottom: 15px; align-items: flex-end; }
    .row-me { justify-content: flex-end; }
    .row-other { justify-content: flex-start; }

    .bubble {
        padding: 12px 18px; border-radius: 20px; max-width: 80%;
        font-size: 15px; line-height: 1.4; word-break: break-all; white-space: pre-wrap;
        box-shadow: 0px 2px 5px rgba(0,0,0,0.05);
    }
    .me { background-color: #ffb7c5; color: white; border-bottom-right-radius: 2px; }
    .other { background-color: white; color: #444; border-bottom-left-radius: 2px; }

    .avatar { width: 40px; height: 40px; border-radius: 50%; margin: 0 10px; border: 2px solid #fff; }
    .nick { font-size: 11px; color: #ff8fa3; margin-bottom: 4px; font-weight: bold; }

    /* 환승연애 폰트 느낌 */
    h1, h2, h3 { color: #ff6b81; font-family: 'Nanum Pen Script', cursive; }
    </style>
    """, unsafe_allow_html=True)

# --- 3. 데이터 초기화 ---
if 'db' not in st.session_state:
    targets = PARTICIPANTS[:]
    while True:
        random.shuffle(targets)
        if all(PARTICIPANTS[i] != targets[i] for i in range(len(PARTICIPANTS))): break

    db = {}
    random.shuffle(AVATARS)
    for i, name in enumerate(PARTICIPANTS):
        db[name] = {
            "nickname": f"{targets[i]}또",
            "avatar": AVATARS[i],
            "target": targets[i],
            "status": "당신은 아직 선택되지 않았습니다",
            "x_chat": [] # 1:1 대화 로그
        }
    st.session_state.db = db
    st.session_state.global_chat = []

# --- 4. 로그인 ---
if 'user' not in st.session_state:
    st.title("💗 당신의 X는 누구입니까?")
    name_select = st.selectbox("당신의 이름을 선택하세요", ["선택하세요", "운영자"] + PARTICIPANTS)
    if name_select == "운영자":
        pw = st.text_input("비밀번호", type="password")
        if st.button("접속"):
            if pw == "1234": st.session_state.user = "운영자"; st.rerun()
    elif name_select != "선택하세요":
        if st.button("시작하기"): st.session_state.user = name_select; st.rerun()

# --- 5. 메인 화면 ---
else:
    user = st.session_state.user
    if user == "운영자":
        st.title("🕶️ 관리자 모드")
        st.table(pd.DataFrame([{"이름": k, "마니또": v['target']} for k, v in st.session_state.db.items()]))
        if st.button("로그아웃"): del st.session_state.user; st.rerun()
    else:
        my = st.session_state.db[user]

        tab1, tab2, tab3 = st.tabs(["💬 핑크톡", "💌 X-대화", "🎯 최종선택"])

        # [탭 1: 단체톡]
        with tab1:
            st.subheader("모두와 소통하는 공간")
            with st.container():
                img = st.file_uploader("이미지 공유", type=['jpg','png'], key="g_img")
                msg = st.chat_input("당신의 마음을 전하세요...")
                if msg or img:
                    st.session_state.global_chat.append({
                        "name": my['nickname'], "avatar": my['avatar'], "msg": msg, "img": img
                    })
                    st.rerun()

            for c in reversed(st.session_state.global_chat):
                is_me = (c['name'] == my['nickname'])
                align = "row-me" if is_me else "row-other"
                b_type = "me" if is_me else "other"

                avatar_html = f'<img src="{c["avatar"]}" class="avatar">'
                content_html = f'<div class="bubble {b_type}">{c["msg"]}</div>' if c['msg'] else ""

                st.markdown(f"""
                    <div class="chat-row {align}">
                        {'' if is_me else avatar_html}
                        <div style="max-width: 70%;">
                            <div class="nick" style="text-align: {'right' if is_me else 'left'};">{c['name']}</div>
                            {content_html}
                        </div>
                        {avatar_html if is_me else ''}
                    </div>
                    """, unsafe_allow_html=True)
                if c['img']: st.image(c['img'], width=200)

        # [탭 2: X-대화 (1:1)]
        with tab2:
            st.subheader(f"내 X({my['target']})와의 대화")
            target_db = st.session_state.db[my['target']]

            x_msg = st.text_input("X에게 보낼 메시지")
            if st.button("전송"):
                # 상대방의 x_chat에 내 닉네임으로 저장
                target_db['x_chat'].append({"sender": my['nickname'], "msg": x_msg})
                st.success("메시지를 보냈습니다.")

            st.divider()
            st.write("📥 나에게 온 익명 메시지")
            for chat in reversed(my['x_chat']):
                st.markdown(f"""
                <div class="chat-row row-other">
                    <div class="bubble other"><b>{chat['sender']}:</b> {chat['msg']}</div>
                </div>
                """, unsafe_allow_html=True)

        # [탭 3: 정답]
        with tab3:
            st.markdown(f"### <center>\"{user}님의 X는 당신을 선택했습니다\"</center>", unsafe_allow_html=True)
            guess = st.selectbox("누가 당신을 챙겨주고 있나요?", ["선택하세요"] + PARTICIPANTS)
            if st.button("확인"):
                real_x = [k for k, v in st.session_state.db.items() if v['target'] == user][0]
                if guess == real_x:
                    st.balloons()
                    st.success("축하합니다! 마음이 통했네요. 💖")
                else:
                    st.error("X는 다른 사람인 것 같아요. 🤫")