# -*- coding: utf-8 -*-
"""app6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpQQ3HhfGKGYGf8oDd6WvPc1eevP1J0k
"""

import streamlit as st
import pandas as pd
import random

# --- 1. 참가자 설정 (24명) ---
PARTICIPANTS = ["단비", "창우", "주희", "온유", "유민", "주형", "예슬", "도현", "성현", "신영", "준일", "주황", "진수", "영찬", "다연", "예원", "주현", "총명", "연제", "윤아", "마리아", "규진", "주한", "건양"]

# --- 2. 핑크 감성 테마 설정 ---
st.set_page_config(page_title="💖 X-Signal", layout="centered")

st.markdown("""
    <style>
    .stApp { background-color: #fff5f7; }
    h1, h2, h3 { color: #ff6b81 !important; }
    .stTabs [data-baseweb="tab-list"] { background-color: transparent; }
    .stTabs [data-baseweb="tab"] { color: #ff8fa3; font-weight: bold; font-size: 16px; }
    /* 채팅 입력창 핑크색 강조 */
    div[data-testid="stChatInput"] { border-radius: 20px; border: 2px solid #ffb7c5; }
    </style>
    """, unsafe_allow_html=True)

# --- 3. 데이터 초기화 (서버당 1회) ---
if 'db' not in st.session_state:
    targets = PARTICIPANTS[:]
    while True:
        random.shuffle(targets)
        if all(PARTICIPANTS[i] != targets[i] for i in range(len(PARTICIPANTS))): break

    db = {}
    for i, name in enumerate(PARTICIPANTS):
        target_name = targets[i]
        db[name] = {
            "nickname": f"{target_name}또",
            "avatar": f"https://api.dicebear.com/7.x/adventurer/svg?seed={name}",
            "target": target_name,
            "x_chat": []
        }
    st.session_state.db = db
    st.session_state.global_chat = []

# --- 4. 로그인 화면 ---
if 'user' not in st.session_state:
    st.markdown("<h1 style='text-align: center;'>💖 X-Signal</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: #ff8fa3;'>당신의 X는 당신을 선택했습니까?</p>", unsafe_allow_html=True)

    with st.expander("입장하기", expanded=True):
        name_select = st.selectbox("본인 이름을 선택하세요", ["선택하세요", "운영자"] + PARTICIPANTS)
        if name_select == "운영자":
            pw = st.text_input("관리자 비밀번호", type="password")
            if st.button("운영자 로그인", use_container_width=True):
                if pw == "1234":
                    st.session_state.user = "운영자"
                    st.rerun()
        elif name_select != "선택하세요":
            if st.button(f"{name_select}님으로 시작", use_container_width=True):
                st.session_state.user = name_select
                st.rerun()

# --- 5. 메인 화면 ---
else:
    user = st.session_state.user

    # [사이드바] 내 정보와 로그아웃 버튼 (절대 안 사라짐)
    with st.sidebar:
        st.markdown(f"# 👤 Profile")
        if user != "운영자":
            my = st.session_state.db[user]
            st.image(my['avatar'], width=120)
            st.markdown(f"### `{my['nickname']}`")
            st.markdown(f"**내가 챙길 X:** <span style='color:#ff6b81; font-size:22px; font-weight:bold;'>{my['target']}</span>", unsafe_allow_html=True)
            st.write("---")

        if st.button("🚪 로그아웃", use_container_width=True):
            del st.session_state.user
            st.rerun()

    if user == "운영자":
        st.title("🕶️ 관리자 모드")
        st.dataframe(pd.DataFrame([{"이름": k, "대상": v['target']} for k, v in st.session_state.db.items()]))
    else:
        my = st.session_state.db[user]
        tab1, tab2, tab3 = st.tabs(["💬 단체톡", "💌 X-대화", "🎯 추리"])

        # [탭 1: 단체톡] - 정식 채팅 UI 사용 (코드 노출 안됨)
        with tab1:
            st.markdown("### 🌸 핑크 시그널 광장")

            # 이미지 업로드 (선택사항)
            up_img = st.file_uploader("이미지 공유", type=['jpg','png'], label_visibility="collapsed")

            # 채팅 입력
            if prompt := st.chat_input("메시지를 입력하세요..."):
                st.session_state.global_chat.append({
                    "name": my['nickname'], "avatar": my['avatar'], "msg": prompt, "img": up_img
                })
                st.rerun()

            # 채팅 출력
            for c in reversed(st.session_state.global_chat):
                with st.chat_message("user", avatar=c['avatar']):
                    st.write(f"**{c['name']}**")
                    if c['msg']: st.write(c['msg'])
                    if c['img']: st.image(c['img'], width=250)

        # [탭 2: X-대화] - 1대1 실제 대화 느낌
        with tab2:
            st.markdown(f"### 💌 {my['target']}님에게 보내는 시그널")
            target_db = st.session_state.db[my['target']]

            x_prompt = st.chat_input("X에게만 보이는 비밀 메시지...", key="x_input")
            if x_prompt:
                # 보낸 기록 (나) / 받은 기록 (상대)
                my['x_chat'].append({"role": "sent", "msg": x_prompt})
                target_db['x_chat'].append({"role": "received", "sender": my['nickname'], "msg": x_prompt})
                st.toast("시그널을 보냈습니다! ❤️")
                st.rerun()

            st.markdown("---")
            for chat in reversed(my['x_chat']):
                if chat['role'] == "received":
                    with st.chat_message("assistant", avatar="💖"):
                        st.write(f"**{chat['sender']}님으로부터**")
                        st.write(chat['msg'])
                else:
                    with st.chat_message("user", avatar="📤"):
                        st.write("**내가 보낸 메시지**")
                        st.write(chat['msg'])

        # [탭 3: 추리]
        with tab3:
            st.markdown("<h2 style='text-align: center;'>당신의 X는 당신을 선택했습니다</h2>", unsafe_allow_html=True)
            guess = st.selectbox("나를 챙겨준 마니또는 누구일까요?", ["선택하세요"] + PARTICIPANTS)
            if st.button("최종 확인", use_container_width=True):
                real_x = [k for k, v in st.session_state.db.items() if v['target'] == user][0]
                if guess == real_x:
                    st.balloons()
                    st.success(f"정답입니다! {real_x}님이 당신의 X였습니다. 💖")
                else:
                    st.error("아쉽지만 정답이 아닙니다. 🤫")