# -*- coding: utf-8 -*-
"""app7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpQQ3HhfGKGYGf8oDd6WvPc1eevP1J0k
"""

import streamlit as st
import pandas as pd
import random

# --- 1. 참가자 설정 (24명) ---
PARTICIPANTS = ["단비", "창우", "주희", "온유", "유민", "주형", "예슬", "도현", "성현", "신영", "준일", "주황", "진수", "영찬", "다연", "예원", "주현", "총명", "연제", "윤아", "마리아", "규진", "주한", "건양"]

# --- 2. 핑크 감성 테마 & UI 레이아웃 설정 ---
st.set_page_config(page_title="💖 X-Signal", layout="centered")

# 배경색, 글자색, 버튼 모양 등 핑크빛 감성 유지
st.markdown("""
    <style>
    .stApp { background: linear-gradient(180deg, #fff5f7 0%, #ffe4e8 100%); }
    h1, h2, h3 { color: #ff6b81 !important; font-family: 'Nanum Pen Script', sans-serif; }
    /* 버튼을 둥글고 핑크하게 */
    .stButton>button { border-radius: 20px; border: 1px solid #ffb7c5; color: #ff6b81; background-color: white; }
    .stButton>button:hover { background-color: #fff5f7; border-color: #ff6b81; }
    /* 탭 메뉴 디자인 */
    .stTabs [data-baseweb="tab-list"] { background-color: transparent; }
    .stTabs [data-baseweb="tab"] { color: #ff8fa3; font-weight: bold; }
    </style>
    """, unsafe_allow_html=True)

# --- 3. 데이터 시스템 초기화 ---
if 'db' not in st.session_state:
    targets = PARTICIPANTS[:]
    while True:
        random.shuffle(targets)
        if all(PARTICIPANTS[i] != targets[i] for i in range(len(PARTICIPANTS))): break

    db = {}
    for i, name in enumerate(PARTICIPANTS):
        target_name = targets[i]
        db[name] = {
            "nickname": f"{target_name}또",
            "avatar": f"https://api.dicebear.com/7.x/adventurer/svg?seed={name}{i}",
            "target": target_name,
            "x_chat": []
        }
    st.session_state.db = db
    st.session_state.global_chat = []

# --- 4. 로그인 화면 ---
if 'user' not in st.session_state:
    st.markdown("<h1 style='text-align: center;'>💖 X-Signal</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: #ff8fa3;'>당신의 X는 당신을 선택했습니까?</p>", unsafe_allow_html=True)

    with st.container(border=True):
        name_select = st.selectbox("당신의 이름을 선택하세요", ["선택하세요", "운영자"] + PARTICIPANTS)
        if name_select == "운영자":
            pw = st.text_input("관리자 비밀번호", type="password")
            if st.button("운영자 접속", use_container_width=True):
                if pw == "1234":
                    st.session_state.user = "운영자"
                    st.rerun()
        elif name_select != "선택하세요":
            if st.button(f"{name_select}님으로 입장하기", use_container_width=True):
                st.session_state.user = name_select
                st.rerun()

# --- 5. 메인 앱 화면 ---
else:
    user = st.session_state.user

    # 사이드바: 내 프로필과 마니또(X) 정보 상시 고정
    with st.sidebar:
        st.markdown(f"## 👤 내 프로필")
        if user != "운영자":
            my = st.session_state.db[user]
            st.image(my['avatar'], width=100)
            st.markdown(f"**닉네임:** `{my['nickname']}`")
            st.markdown(f"**당신의 X(대상):** <span style='color:#ff6b81; font-size:20px; font-weight:bold;'>{my['target']}</span>", unsafe_allow_html=True)
            st.divider()

        if st.button("🚪 로그아웃", use_container_width=True):
            del st.session_state.user
            st.rerun()

    if user == "운영자":
        st.title("🕶️ 관리자 패널")
        m_df = pd.DataFrame([{"이름": k, "X(대상)": v['target']} for k, v in st.session_state.db.items()])
        st.dataframe(m_df, use_container_width=True)

    else:
        my = st.session_state.db[user]
        tab1, tab2, tab3 = st.tabs(["💬 핑크톡", "💌 X-대화", "🎯 추리"])

        # [탭 1: 단체톡] - 코드가 노출되지 않는 정식 채팅 UI
        with tab1:
            st.markdown("### 🌸 핑크 시그널 광장")

            with st.container():
                col1, col2 = st.columns([3, 1])
                # 이미지 업로더를 위로 배치하여 가독성 확보
                chat_img = col2.file_uploader("🖼️", type=['jpg','png'], label_visibility="collapsed")
                chat_msg = st.chat_input("익명으로 메시지를 남기세요...")

                if chat_msg:
                    st.session_state.global_chat.append({
                        "name": my['nickname'], "avatar": my['avatar'], "msg": chat_msg, "img": chat_img
                    })
                    st.rerun()

            for c in reversed(st.session_state.global_chat):
                with st.chat_message("user", avatar=c['avatar']):
                    st.write(f"**{c['name']}**")
                    if c['msg']: st.write(c['msg'])
                    if c['img']: st.image(c['img'], width=250)

        # [탭 2: X-대화] - 1:1 대화방 형식
        with tab2:
            st.markdown(f"### 💌 {my['target']}님과의 비밀 대화")
            target_db = st.session_state.db[my['target']]

            x_input = st.chat_input("X에게만 보이는 메시지를 보내세요...", key="x_chat_input")
            if x_input:
                my['x_chat'].append({"role": "sent", "msg": x_input})
                target_db['x_chat'].append({"role": "received", "sender": my['nickname'], "msg": x_input})
                st.toast("시그널이 전송되었습니다! ❤️")
                st.rerun()

            st.divider()
            for chat in reversed(my['x_chat']):
                if chat['role'] == "received":
                    with st.chat_message("assistant", avatar="💖"):
                        st.write(f"**{chat['sender']}님으로부터**")
                        st.write(chat['msg'])
                else:
                    with st.chat_message("user", avatar="📤"):
                        st.write("**내가 보낸 메시지**")
                        st.write(chat['msg'])

        # [탭 3: 추리] - 환승연애 핵심 문구 강조
        with tab3:
            st.markdown("<div style='text-align: center; padding: 30px; border-radius: 20px; background-color: white; border: 2px solid #ffb7c5;'>", unsafe_allow_html=True)
            st.markdown(f"## \"당신의 X는 당신을 선택했습니다\"")
            st.markdown("</div>", unsafe_allow_html=True)

            st.write("")
            guess = st.selectbox("누가 당신을 마니또로 챙기고 있나요?", ["선택하세요"] + PARTICIPANTS)
            if st.button("최종 확인", use_container_width=True):
                real_x = [k for k, v in st.session_state.db.items() if v['target'] == user][0]
                if guess == real_x:
                    st.balloons()
                    st.success(f"정답입니다! {real_x}님이 당신의 마니또였습니다. 💖")
                else:
                    st.error("아쉽지만 정답이 아닙니다. 다시 추리해보세요! 🤫")